CREATE TABLE IF NOT EXISTS inpatient (
  HospitalServiceArea TEXT,
  HospitalCounty TEXT,
  OperatingCertificateNumber TEXT,
  PermanentFacilityId TEXT,
  FacilityName TEXT,
  AgeGroup TEXT,
  ZipCode3Digits TEXT,
  Gender TEXT,
  Race TEXT,
  Ethnicity TEXT,
  RaceEthnicity TEXT,
  LengthOfStay INT,
  AdmissionType TEXT,
  PatientDisposition TEXT,
  DischargeYear INT,
  CCSRDiagnosisCode TEXT,
  CCSRDiagnosisDescription TEXT,
  CCSRProcedureCode TEXT,
  CCSRProcedureDescription TEXT,
  APRDRGCode INT,
  APRDRGDescription TEXT,
  APRMDCCode INT,
  APRMDCDescription TEXT,
  APRSeverityOfIllnessCode INT,
  APRSeverityOfIllnessDescription TEXT,
  APRRiskOfMortality TEXT,
  APRMedicalSurgicalDescription TEXT,
  PaymentTypology1 TEXT,
  PaymentTypology2 TEXT,
  PaymentTypology3 TEXT,
  BirthWeight INT,
  EmergencyDepartmentIndicator TEXT,
  TotalCharges DECIMAL(14, 2),
  TotalCosts DECIMAL(14, 2)
);
